export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const FETCH_EMPLOYEE = "FETCH_EMPLOYEE";
export const FETCH_ALL_EMPLOYEES = "FETCH_ALL_EMPLOYEES";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const SEARCH_EMPLOYEE = "SEARCH_EMPLOYEE";
